---
title: "Welcome to the DSL R Workshops"
output: 
  html_document: 
    theme: readable
    highlight: pygments
urlcolor: red
---

<style type="text/css">
  body{
  font-size: 22pt;
}
</style>


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The materials for the R workshops will be hosted on Microsoft Teams. 

## How do I join?

1. Open [Teams](https://info.lse.ac.uk/staff/divisions/dts/essentials/setting-up-microsoft-teams)   
2. Go to the teams overview on the left hand bar    
3. Click on **'Join or create team'** button    
4. Enter the code **4qgm3qm**   
5. Open the DSL-R-Workshops team page   
6. Find the relevant document/s by searching the channels on the sidebar

## How do I use the files?

- We will be using `.Rmd` files
- Download the files that are relevant for the workshop you are working on
- For example, if you are starting R Fundamentals, download the `r-fundamentals_1.Rmd` from the *R-Fundamentals* channel
- Load the `.Rmd` files into RStudio
- Start working through the examples and exercises

<br>

***

## What does R Fundamentals cover?

<font size="5">

**R Fundamentals 1**

Get started with R and RStudio, working with variables to perform calculations 

**R Fundamentals 2**

Start working with vectors to perform summary statistics on data as well as accessing parts of your data (indexing)

**R Fundamentals 3**

An introduction to using text, factors (categorical data), and how to change the data type

**R Fundamentals 4**

Start using data frames which are like Excel spreadsheets in structure. We will cover how to use this important data type to perform summary statistics

**R Fundamentals 5**

Start loading data into R, and in the process learn about packages (extensions to R) and what how to work with pathways/directories

**R Fundamentals 6**

An introduction to conditional operators and logic, which we use to filter and categorise data

**R Fundamentals 7**

Start working with list and matrix data types, where we cover how to make, access data, and their general uses

</font> 
<br>

***

## What does R Data Wrangling and Visualisation cover?

<font size="5">

**R Data Wrangling 1**

Introduction to the tidyverse through dplyr and piping your workflow. We will be covering how to select columns and filter rows, as well as general tips along the way

**R Data Wrangling 2**

Start manipulating columns of data (creation, modification, or removal of columns) as well as cleaning up your column names. 

**R Data Wrangling 3**

An introduction to relational joins, cross tabulation, and aggregation (split, apply, combine)

**R Data Visualisation 1**

Get started with ggplot2 where you will mark scatter and bar plots to visualise your data

**R Data Visualisation 2**

Continue learning ggplot2 by making box plots, histograms, and time series visualisations

</font> 

----

<font size="5">

## Installing R and RStudio

Below are step by step instructions for getting R and RStudio installed in your personal laptop. RStudio is a popular tool for using R. 

If you are wanting to install R and RStudio on a device whereby you do not have administrative privilages, contact `tech.support@lse.ac.uk`

## Windows install

### Install R

To install R, you need to download the installer from the [R website](https://cloud.r-project.org/bin/windows/ ). Once downloaded, follow the installation instructions.  

### Install RStudio

Finally, we install RStudio. To do so, we download it from the [Posit website](https://posit.co/download/rstudio-desktop/), and follow the installation instructions. 

Once installed, open RStudio. If the installation of all the above software has worked you should see three panes, with one of them telling you the version of R you have installed. 

## Mac install

### Install R

To install R on your Mac you need to know the type of processor your Mac uses. This is straightforward to find out:

1) On the top navigation bar on your Mac, click on the apple icon
2) From the drop down menu, select *About This Mac*
3) In *Overview* you will find the information about your Mac. If you have an *Intel Mac*, you will see the processor row, which has information that includes *Intel*. If you have an M1 Mac, you will see chip and M1 in the *Overview*

If you have a *M1 Mac* you will need to download the R package that says something like: *R-4.2.2-arm64.pkg*. If you have a *Intel Mac* you will need to download the R package that says something like: *R-4.2.2.pkg*

To install R, you need to download the installer from the [R website](https://cloud.r-project.org/bin/macosx/). Once downloaded, follow the installation instructions.  

### Install XQuartz

To run R on a Mac operating system, XQuartz is required. You can install it by following [this link](https://www.xquartz.org/), downloading it and following the installation instructions. 

### Install RStudio

Finally, we install RStudio. To do so, we download it from the [Posit website](https://posit.co/download/rstudio-desktop/), and follow the installation instructions. 

Once installed, open RStudio. If the installation of all the above software has worked you should see three panes, with one of them telling you the version of R you have installed. 

## Installing R and RStudio installation issues

If your installation for R and RStudio did not work, this is likely because your computer is running an older operating system. In these cases you will have to install an older version of the software. For help with this please contact `digital.skills.lab@lse.ac.uk`. 

</font> 
